import React from "react";
import { Button } from "@apollo/space-kit/Button";
import { colors } from "@apollo/space-kit/colors";
import { IconUpload } from "@apollo/space-kit/icons/IconUpload";
import { IconComment } from "@apollo/space-kit/icons/IconComment";
import { IconLike } from "@apollo/space-kit/icons/IconLike";
import { IconHistory } from "@apollo/space-kit/icons/IconHistory";
import { SlideBody } from "../../components/deck/SlideBody";
import { Header } from "./Header";

export default function Slide() {
  return (
    <SlideBody header={<Header title="Superpowers of Data-Driven Apps" />}>
      <div className="flex-1 flex pl-4 h-full">
        <ul className="list-none flex-1">
          <li>
            <Button
              size="large"
              color={colors.indigo.dark}
              className="px-4 my-4 mr-4"
            >
              Login
            </Button>
            Personalized to <em>you</em>
          </li>
          <li>
            <Button
              size="large"
              color={colors.indigo.dark}
              className="px-4 my-4 mr-4"
            >
              <IconUpload />
            </Button>
            Content generated by <em>you</em>
          </li>
          <li>
            <Button
              size="large"
              color={colors.indigo.dark}
              className="px-4 my-4 mr-4"
            >
              <IconComment />
            </Button>
            Collaborative
          </li>
          <li>
            <Button
              size="large"
              color={colors.indigo.dark}
              className="px-4 my-4 mr-4"
            >
              <IconLike />
            </Button>
            Interactive
          </li>
          <li>
            <Button
              size="large"
              color={colors.indigo.dark}
              className="px-4 my-4 mr-4"
            >
              <IconHistory />
            </Button>
            New stuff ALL THE TIME
          </li>
        </ul>
        <div
          className="rounded-lg flex-1 h-full"
          style={{
            backgroundSize: "cover",
            backgroundPosition: "center",
            backgroundImage: 'url("/img/slack.jpg")',
            backgroundRepeat: "no-repeat",
            opacity: 0.8,
          }}
        />
      </div>
    </SlideBody>
  );
}
